package com.covid.model.db;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Allergy generated by hbm2java
 */
@Entity
@Table(name = "allergy", schema = "release1")
public class Allergy implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -5134288003364639525L;
	private int allergyId;
	private int patientId;
	private String allergenType;
	private String allergenCodeSystem;
	private String allergenConceptCode;
	private String allergenDescription;
	private String allergicRxnCodeSystem;
	private String allergicRxnConceptCode;
	private String allergicRxnDescription;
	private String allergySeverity;
	private Boolean isActive;
	private Integer durationNum;
	private String durationUnits;

	public Allergy() {
	}

	public Allergy(final int allergyId, final int patientId) {
		this.allergyId = allergyId;
		this.patientId = patientId;
	}

	public Allergy(final int allergyId, final int patientId, final String allergenType, final String allergenCodeSystem,
			final String allergenConceptCode, final String allergenDescription, final String allergicRxnCodeSystem,
			final String allergicRxnConceptCode, final String allergicRxnDescription, final String allergySeverity,
			final Boolean isActive, final Integer durationNum, final String durationUnits) {
		this.allergyId = allergyId;
		this.patientId = patientId;
		this.allergenType = allergenType;
		this.allergenCodeSystem = allergenCodeSystem;
		this.allergenConceptCode = allergenConceptCode;
		this.allergenDescription = allergenDescription;
		this.allergicRxnCodeSystem = allergicRxnCodeSystem;
		this.allergicRxnConceptCode = allergicRxnConceptCode;
		this.allergicRxnDescription = allergicRxnDescription;
		this.allergySeverity = allergySeverity;
		this.isActive = isActive;
		this.durationNum = durationNum;
		this.durationUnits = durationUnits;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "allergy_id", unique = true, nullable = false)
	public int getAllergyId() {
		return this.allergyId;
	}

	public void setAllergyId(final int allergyId) {
		this.allergyId = allergyId;
	}

	@Column(name = "patient_id", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(final int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "allergen_type", length = 32)
	public String getAllergenType() {
		return this.allergenType;
	}

	public void setAllergenType(final String allergenType) {
		this.allergenType = allergenType;
	}

	@Column(name = "allergen_code_system", length = 32)
	public String getAllergenCodeSystem() {
		return this.allergenCodeSystem;
	}

	public void setAllergenCodeSystem(final String allergenCodeSystem) {
		this.allergenCodeSystem = allergenCodeSystem;
	}

	@Column(name = "allergen_concept_code", length = 32)
	public String getAllergenConceptCode() {
		return this.allergenConceptCode;
	}

	public void setAllergenConceptCode(final String allergenConceptCode) {
		this.allergenConceptCode = allergenConceptCode;
	}

	@Column(name = "allergen_description")
	public String getAllergenDescription() {
		return this.allergenDescription;
	}

	public void setAllergenDescription(final String allergenDescription) {
		this.allergenDescription = allergenDescription;
	}

	@Column(name = "allergic_rxn_code_system", length = 32)
	public String getAllergicRxnCodeSystem() {
		return this.allergicRxnCodeSystem;
	}

	public void setAllergicRxnCodeSystem(final String allergicRxnCodeSystem) {
		this.allergicRxnCodeSystem = allergicRxnCodeSystem;
	}

	@Column(name = "allergic_rxn_concept_code", length = 32)
	public String getAllergicRxnConceptCode() {
		return this.allergicRxnConceptCode;
	}

	public void setAllergicRxnConceptCode(final String allergicRxnConceptCode) {
		this.allergicRxnConceptCode = allergicRxnConceptCode;
	}

	@Column(name = "allergic_rxn_description")
	public String getAllergicRxnDescription() {
		return this.allergicRxnDescription;
	}

	public void setAllergicRxnDescription(final String allergicRxnDescription) {
		this.allergicRxnDescription = allergicRxnDescription;
	}

	@Column(name = "allergy_severity", length = 10)
	public String getAllergySeverity() {
		return this.allergySeverity;
	}

	public void setAllergySeverity(final String allergySeverity) {
		this.allergySeverity = allergySeverity;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(final Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "duration_num")
	public Integer getDurationNum() {
		return this.durationNum;
	}

	public void setDurationNum(final Integer durationNum) {
		this.durationNum = durationNum;
	}

	@Column(name = "duration_units", length = 10)
	public String getDurationUnits() {
		return this.durationUnits;
	}

	public void setDurationUnits(final String durationUnits) {
		this.durationUnits = durationUnits;
	}

}
