package com.covid.model.db;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AppHeartbeat generated by hbm2java
 */
@Entity
@Table(name = "app_heartbeat", schema = "release1")
public class AppHeartbeat implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 2797028966833343136L;
	private int appHeartbeatId;
	private int deviceAppId;
	private Date heartbeatDateTime;
	private String heartBeatIp4Address;
	private String heartBeatIp6Address;
	private String heartbeatStatus;

	public AppHeartbeat() {
	}

	public AppHeartbeat(final int appHeartbeatId, final int deviceAppId) {
		this.appHeartbeatId = appHeartbeatId;
		this.deviceAppId = deviceAppId;
	}

	public AppHeartbeat(final int appHeartbeatId, final int deviceAppId, final Date heartbeatDateTime,
			final String heartBeatIp4Address, final String heartBeatIp6Address, final String heartbeatStatus) {
		this.appHeartbeatId = appHeartbeatId;
		this.deviceAppId = deviceAppId;
		this.heartbeatDateTime = heartbeatDateTime;
		this.heartBeatIp4Address = heartBeatIp4Address;
		this.heartBeatIp6Address = heartBeatIp6Address;
		this.heartbeatStatus = heartbeatStatus;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "app_heartbeat_id", unique = true, nullable = false)
	public int getAppHeartbeatId() {
		return this.appHeartbeatId;
	}

	public void setAppHeartbeatId(final int appHeartbeatId) {
		this.appHeartbeatId = appHeartbeatId;
	}

	@Column(name = "device_app_id", nullable = false)
	public int getDeviceAppId() {
		return this.deviceAppId;
	}

	public void setDeviceAppId(final int deviceAppId) {
		this.deviceAppId = deviceAppId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "heartbeat_date_time", length = 29)
	public Date getHeartbeatDateTime() {
		return this.heartbeatDateTime;
	}

	public void setHeartbeatDateTime(final Date heartbeatDateTime) {
		this.heartbeatDateTime = heartbeatDateTime;
	}

	@Column(name = "heart_beat_ip4_address", length = 16)
	public String getHeartBeatIp4Address() {
		return this.heartBeatIp4Address;
	}

	public void setHeartBeatIp4Address(final String heartBeatIp4Address) {
		this.heartBeatIp4Address = heartBeatIp4Address;
	}

	@Column(name = "heart_beat_ip6_address", length = 40)
	public String getHeartBeatIp6Address() {
		return this.heartBeatIp6Address;
	}

	public void setHeartBeatIp6Address(final String heartBeatIp6Address) {
		this.heartBeatIp6Address = heartBeatIp6Address;
	}

	@Column(name = "heartbeat_status", length = 10)
	public String getHeartbeatStatus() {
		return this.heartbeatStatus;
	}

	public void setHeartbeatStatus(final String heartbeatStatus) {
		this.heartbeatStatus = heartbeatStatus;
	}

}
