package com.covid.model.db;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Demographics generated by hbm2java
 */
@Entity
@Table(name = "demographics", schema = "release1")
public class Demographics implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2734948300537873206L;
	private int userId;
	private String nationality;
	private String residencyStatus;
	private String occupation;
	private Integer emergencyContactId1;
	private String emerContact1RelToPat;
	private Integer emergencyContactId2;
	private String emerContact2RelToPat;
	private Integer nextOfKinId1;
	private String nextOfKin1RelToPat;
	private Integer nextOfKinId2;
	private String nextOfKin2RelToPat;

	public Demographics() {
	}

	public Demographics(final int userId) {
		this.userId = userId;
	}

	public Demographics(final int userId, final String nationality, final String residencyStatus,
			final String occupation, final Integer emergencyContactId1, final String emerContact1RelToPat,
			final Integer emergencyContactId2, final String emerContact2RelToPat, final Integer nextOfKinId1,
			final String nextOfKin1RelToPat, final Integer nextOfKinId2, final String nextOfKin2RelToPat) {
		this.userId = userId;
		this.nationality = nationality;
		this.residencyStatus = residencyStatus;
		this.occupation = occupation;
		this.emergencyContactId1 = emergencyContactId1;
		this.emerContact1RelToPat = emerContact1RelToPat;
		this.emergencyContactId2 = emergencyContactId2;
		this.emerContact2RelToPat = emerContact2RelToPat;
		this.nextOfKinId1 = nextOfKinId1;
		this.nextOfKin1RelToPat = nextOfKin1RelToPat;
		this.nextOfKinId2 = nextOfKinId2;
		this.nextOfKin2RelToPat = nextOfKin2RelToPat;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(final int userId) {
		this.userId = userId;
	}

	@Column(name = "nationality", length = 32)
	public String getNationality() {
		return this.nationality;
	}

	public void setNationality(final String nationality) {
		this.nationality = nationality;
	}

	@Column(name = "residency_status", length = 32)
	public String getResidencyStatus() {
		return this.residencyStatus;
	}

	public void setResidencyStatus(final String residencyStatus) {
		this.residencyStatus = residencyStatus;
	}

	@Column(name = "occupation", length = 32)
	public String getOccupation() {
		return this.occupation;
	}

	public void setOccupation(final String occupation) {
		this.occupation = occupation;
	}

	@Column(name = "emergency_contact_id_1")
	public Integer getEmergencyContactId1() {
		return this.emergencyContactId1;
	}

	public void setEmergencyContactId1(final Integer emergencyContactId1) {
		this.emergencyContactId1 = emergencyContactId1;
	}

	@Column(name = "emer_contact_1_rel_to_pat", length = 32)
	public String getEmerContact1RelToPat() {
		return this.emerContact1RelToPat;
	}

	public void setEmerContact1RelToPat(final String emerContact1RelToPat) {
		this.emerContact1RelToPat = emerContact1RelToPat;
	}

	@Column(name = "emergency_contact_id_2")
	public Integer getEmergencyContactId2() {
		return this.emergencyContactId2;
	}

	public void setEmergencyContactId2(final Integer emergencyContactId2) {
		this.emergencyContactId2 = emergencyContactId2;
	}

	@Column(name = "emer_contact_2_rel_to_pat", length = 32)
	public String getEmerContact2RelToPat() {
		return this.emerContact2RelToPat;
	}

	public void setEmerContact2RelToPat(final String emerContact2RelToPat) {
		this.emerContact2RelToPat = emerContact2RelToPat;
	}

	@Column(name = "next_of_kin_id_1")
	public Integer getNextOfKinId1() {
		return this.nextOfKinId1;
	}

	public void setNextOfKinId1(final Integer nextOfKinId1) {
		this.nextOfKinId1 = nextOfKinId1;
	}

	@Column(name = "next_of_kin_1_rel_to_pat", length = 32)
	public String getNextOfKin1RelToPat() {
		return this.nextOfKin1RelToPat;
	}

	public void setNextOfKin1RelToPat(final String nextOfKin1RelToPat) {
		this.nextOfKin1RelToPat = nextOfKin1RelToPat;
	}

	@Column(name = "next_of_kin_id_2")
	public Integer getNextOfKinId2() {
		return this.nextOfKinId2;
	}

	public void setNextOfKinId2(final Integer nextOfKinId2) {
		this.nextOfKinId2 = nextOfKinId2;
	}

	@Column(name = "next_of_kin_2_rel_to_pat", length = 32)
	public String getNextOfKin2RelToPat() {
		return this.nextOfKin2RelToPat;
	}

	public void setNextOfKin2RelToPat(final String nextOfKin2RelToPat) {
		this.nextOfKin2RelToPat = nextOfKin2RelToPat;
	}

}
