package com.covid.model.db;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeviceLocation generated by hbm2java
 */
@Entity
@Table(name = "device_location", schema = "release1")
public class DeviceLocation implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -5091202398470792303L;
	private int deviceLocationId;
	private int deviceAppId;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private Integer locationId;
	private Integer addressId;
	private String locationServiceType;
	private Date locationDateTime;
	private String locationCheckReason;
	private String locationCheckResult;
	private String geofenceStatus;
	private String geofenceAction;
	private String comments;

	public DeviceLocation() {
	}

	public DeviceLocation(final int deviceLocationId, final int deviceAppId) {
		this.deviceLocationId = deviceLocationId;
		this.deviceAppId = deviceAppId;
	}

	public DeviceLocation(final int deviceLocationId, final int deviceAppId, final BigDecimal latitude,
			final BigDecimal longitude, final Integer locationId, final Integer addressId,
			final String locationServiceType, final Date locationDateTime, final String locationCheckReason,
			final String locationCheckResult, final String geofenceStatus, final String geofenceAction,
			final String comments) {
		this.deviceLocationId = deviceLocationId;
		this.deviceAppId = deviceAppId;
		this.latitude = latitude;
		this.longitude = longitude;
		this.locationId = locationId;
		this.addressId = addressId;
		this.locationServiceType = locationServiceType;
		this.locationDateTime = locationDateTime;
		this.locationCheckReason = locationCheckReason;
		this.locationCheckResult = locationCheckResult;
		this.geofenceStatus = geofenceStatus;
		this.geofenceAction = geofenceAction;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "device_location_id", unique = true, nullable = false)
	public int getDeviceLocationId() {
		return this.deviceLocationId;
	}

	public void setDeviceLocationId(final int deviceLocationId) {
		this.deviceLocationId = deviceLocationId;
	}

	@Column(name = "device_app_id", nullable = false)
	public int getDeviceAppId() {
		return this.deviceAppId;
	}

	public void setDeviceAppId(final int deviceAppId) {
		this.deviceAppId = deviceAppId;
	}

	@Column(name = "latitude", precision = 10, scale = 8)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(final BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 11, scale = 8)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(final BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "location_id")
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(final Integer locationId) {
		this.locationId = locationId;
	}

	@Column(name = "address_id")
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(final Integer addressId) {
		this.addressId = addressId;
	}

	@Column(name = "location_service_type", length = 10)
	public String getLocationServiceType() {
		return this.locationServiceType;
	}

	public void setLocationServiceType(final String locationServiceType) {
		this.locationServiceType = locationServiceType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "location_date_time", length = 29)
	public Date getLocationDateTime() {
		return this.locationDateTime;
	}

	public void setLocationDateTime(final Date locationDateTime) {
		this.locationDateTime = locationDateTime;
	}

	@Column(name = "location_check_reason", length = 16)
	public String getLocationCheckReason() {
		return this.locationCheckReason;
	}

	public void setLocationCheckReason(final String locationCheckReason) {
		this.locationCheckReason = locationCheckReason;
	}

	@Column(name = "location_check_result", length = 16)
	public String getLocationCheckResult() {
		return this.locationCheckResult;
	}

	public void setLocationCheckResult(final String locationCheckResult) {
		this.locationCheckResult = locationCheckResult;
	}

	@Column(name = "geofence_status", length = 16)
	public String getGeofenceStatus() {
		return this.geofenceStatus;
	}

	public void setGeofenceStatus(final String geofenceStatus) {
		this.geofenceStatus = geofenceStatus;
	}

	@Column(name = "geofence_action")
	public String getGeofenceAction() {
		return this.geofenceAction;
	}

	public void setGeofenceAction(final String geofenceAction) {
		this.geofenceAction = geofenceAction;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(final String comments) {
		this.comments = comments;
	}

}
