package com.covid.model.db;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * HealthPro generated by hbm2java
 */
@Entity
@Table(name = "health_pro", schema = "release1")
public class HealthPro implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8259417342393644376L;
	private int healthProId;
	private int jobId;
	private Integer supervisorId;
	private String jobTitle;
	private Integer workLocationId;
	private Boolean isActive;

	public HealthPro() {
	}

	public HealthPro(final int healthProId, final int jobId) {
		this.healthProId = healthProId;
		this.jobId = jobId;
	}

	public HealthPro(final int healthProId, final int jobId, final Integer supervisorId, final String jobTitle,
			final Integer workLocationId, final Boolean isActive) {
		this.healthProId = healthProId;
		this.jobId = jobId;
		this.supervisorId = supervisorId;
		this.jobTitle = jobTitle;
		this.workLocationId = workLocationId;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "health_pro_id", unique = true, nullable = false)
	public int getHealthProId() {
		return this.healthProId;
	}

	public void setHealthProId(final int healthProId) {
		this.healthProId = healthProId;
	}

	@Column(name = "job_id", nullable = false)
	public int getJobId() {
		return this.jobId;
	}

	public void setJobId(final int jobId) {
		this.jobId = jobId;
	}

	@Column(name = "supervisor_id")
	public Integer getSupervisorId() {
		return this.supervisorId;
	}

	public void setSupervisorId(final Integer supervisorId) {
		this.supervisorId = supervisorId;
	}

	@Column(name = "job_title", length = 32)
	public String getJobTitle() {
		return this.jobTitle;
	}

	public void setJobTitle(final String jobTitle) {
		this.jobTitle = jobTitle;
	}

	@Column(name = "work_location_id")
	public Integer getWorkLocationId() {
		return this.workLocationId;
	}

	public void setWorkLocationId(final Integer workLocationId) {
		this.workLocationId = workLocationId;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(final Boolean isActive) {
		this.isActive = isActive;
	}

}
