package com.covid.model.db;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HealthCheckHistory generated by hbm2java
 */
@Entity
@Table(name = "health_check_history", schema = "release1")
public class HealthCheckHistory implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1240244796676339981L;
	private int healthHistoryId;
	private int patientId;
	private Integer enteredByUserId;
	private String healthCheckByUserType;
	private Integer appHeartbeatId;
	private Integer locationId;
	private Date healthCheckDateTime;
	private String healthCheckReason;
	private Boolean coughPresent;
	private Boolean feverPresent;
	private Boolean breathingDifficultyPresent;
	private String progressStatus;
	private Double temperatureCelsius;
	private Integer heartRatePerMin;
	private Integer respRatePerMin;
	private Integer spo2Percent;
	private Integer systolicBpMmhg;
	private Integer diastolicBpMmhg;
	private String comments;

	public HealthCheckHistory() {
	}

	public HealthCheckHistory(final int healthHistoryId, final int patientId) {
		this.healthHistoryId = healthHistoryId;
		this.patientId = patientId;
	}

	public HealthCheckHistory(final int healthHistoryId, final int patientId, final Integer enteredByUserId,
			final String healthCheckByUserType, final Integer appHeartbeatId, final Integer locationId,
			final Date healthCheckDateTime, final String healthCheckReason, final Boolean coughPresent,
			final Boolean feverPresent, final Boolean breathingDifficultyPresent, final String progressStatus,
			final Double temperatureCelsius, final Integer heartRatePerMin, final Integer respRatePerMin,
			final Integer spo2Percent, final Integer systolicBpMmhg, final Integer diastolicBpMmhg,
			final String comments) {
		this.healthHistoryId = healthHistoryId;
		this.patientId = patientId;
		this.enteredByUserId = enteredByUserId;
		this.healthCheckByUserType = healthCheckByUserType;
		this.appHeartbeatId = appHeartbeatId;
		this.locationId = locationId;
		this.healthCheckDateTime = healthCheckDateTime;
		this.healthCheckReason = healthCheckReason;
		this.coughPresent = coughPresent;
		this.feverPresent = feverPresent;
		this.breathingDifficultyPresent = breathingDifficultyPresent;
		this.progressStatus = progressStatus;
		this.temperatureCelsius = temperatureCelsius;
		this.heartRatePerMin = heartRatePerMin;
		this.respRatePerMin = respRatePerMin;
		this.spo2Percent = spo2Percent;
		this.systolicBpMmhg = systolicBpMmhg;
		this.diastolicBpMmhg = diastolicBpMmhg;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "health_history_id", unique = true, nullable = false)
	public int getHealthHistoryId() {
		return this.healthHistoryId;
	}

	public void setHealthHistoryId(final int healthHistoryId) {
		this.healthHistoryId = healthHistoryId;
	}

	@Column(name = "patient_id", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(final int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "entered_by_user_id")
	public Integer getEnteredByUserId() {
		return this.enteredByUserId;
	}

	public void setEnteredByUserId(final Integer enteredByUserId) {
		this.enteredByUserId = enteredByUserId;
	}

	@Column(name = "health_check_by_user_type", length = 32)
	public String getHealthCheckByUserType() {
		return this.healthCheckByUserType;
	}

	public void setHealthCheckByUserType(final String healthCheckByUserType) {
		this.healthCheckByUserType = healthCheckByUserType;
	}

	@Column(name = "app_heartbeat_id")
	public Integer getAppHeartbeatId() {
		return this.appHeartbeatId;
	}

	public void setAppHeartbeatId(final Integer appHeartbeatId) {
		this.appHeartbeatId = appHeartbeatId;
	}

	@Column(name = "location_id")
	public Integer getLocationId() {
		return this.locationId;
	}

	public void setLocationId(final Integer locationId) {
		this.locationId = locationId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "health_check_date_time", length = 29)
	public Date getHealthCheckDateTime() {
		return this.healthCheckDateTime;
	}

	public void setHealthCheckDateTime(final Date healthCheckDateTime) {
		this.healthCheckDateTime = healthCheckDateTime;
	}

	@Column(name = "health_check_reason")
	public String getHealthCheckReason() {
		return this.healthCheckReason;
	}

	public void setHealthCheckReason(final String healthCheckReason) {
		this.healthCheckReason = healthCheckReason;
	}

	@Column(name = "cough_present")
	public Boolean getCoughPresent() {
		return this.coughPresent;
	}

	public void setCoughPresent(final Boolean coughPresent) {
		this.coughPresent = coughPresent;
	}

	@Column(name = "fever_present")
	public Boolean getFeverPresent() {
		return this.feverPresent;
	}

	public void setFeverPresent(final Boolean feverPresent) {
		this.feverPresent = feverPresent;
	}

	@Column(name = "breathing_difficulty_present")
	public Boolean getBreathingDifficultyPresent() {
		return this.breathingDifficultyPresent;
	}

	public void setBreathingDifficultyPresent(final Boolean breathingDifficultyPresent) {
		this.breathingDifficultyPresent = breathingDifficultyPresent;
	}

	@Column(name = "progress_status", length = 32)
	public String getProgressStatus() {
		return this.progressStatus;
	}

	public void setProgressStatus(final String progressStatus) {
		this.progressStatus = progressStatus;
	}

	@Column(name = "temperature_celsius", precision = 17, scale = 17)
	public Double getTemperatureCelsius() {
		return this.temperatureCelsius;
	}

	public void setTemperatureCelsius(final Double temperatureCelsius) {
		this.temperatureCelsius = temperatureCelsius;
	}

	@Column(name = "heart_rate_per_min")
	public Integer getHeartRatePerMin() {
		return this.heartRatePerMin;
	}

	public void setHeartRatePerMin(final Integer heartRatePerMin) {
		this.heartRatePerMin = heartRatePerMin;
	}

	@Column(name = "resp_rate_per_min")
	public Integer getRespRatePerMin() {
		return this.respRatePerMin;
	}

	public void setRespRatePerMin(final Integer respRatePerMin) {
		this.respRatePerMin = respRatePerMin;
	}

	@Column(name = "spo2_percent")
	public Integer getSpo2Percent() {
		return this.spo2Percent;
	}

	public void setSpo2Percent(final Integer spo2Percent) {
		this.spo2Percent = spo2Percent;
	}

	@Column(name = "systolic_bp_mmhg")
	public Integer getSystolicBpMmhg() {
		return this.systolicBpMmhg;
	}

	public void setSystolicBpMmhg(final Integer systolicBpMmhg) {
		this.systolicBpMmhg = systolicBpMmhg;
	}

	@Column(name = "diastolic_bp_mmhg")
	public Integer getDiastolicBpMmhg() {
		return this.diastolicBpMmhg;
	}

	public void setDiastolicBpMmhg(final Integer diastolicBpMmhg) {
		this.diastolicBpMmhg = diastolicBpMmhg;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(final String comments) {
		this.comments = comments;
	}

}
