package com.covid.model.db;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LocationHierarchy generated by hbm2java
 */
@Entity
@Table(name = "location_hierarchy", schema = "release1")
public class LocationHierarchy implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -3685614411087119194L;
	private int locationId;
	private String locationName;
	private String locationAbbr;
	private Boolean assignPatients;
	private Integer parentLocationId;
	private String countryCode;
	private Integer addressId;

	public LocationHierarchy() {
	}

	public LocationHierarchy(final int locationId) {
		this.locationId = locationId;
	}

	public LocationHierarchy(final int locationId, final String locationName, final String locationAbbr,
			final Boolean assignPatients, final Integer parentLocationId, final String countryCode,
			final Integer addressId) {
		this.locationId = locationId;
		this.locationName = locationName;
		this.locationAbbr = locationAbbr;
		this.assignPatients = assignPatients;
		this.parentLocationId = parentLocationId;
		this.countryCode = countryCode;
		this.addressId = addressId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "location_id", unique = true, nullable = false)
	public int getLocationId() {
		return this.locationId;
	}

	public void setLocationId(final int locationId) {
		this.locationId = locationId;
	}

	@Column(name = "location_name")
	public String getLocationName() {
		return this.locationName;
	}

	public void setLocationName(final String locationName) {
		this.locationName = locationName;
	}

	@Column(name = "location_abbr", length = 32)
	public String getLocationAbbr() {
		return this.locationAbbr;
	}

	public void setLocationAbbr(final String locationAbbr) {
		this.locationAbbr = locationAbbr;
	}

	@Column(name = "assign_patients")
	public Boolean getAssignPatients() {
		return this.assignPatients;
	}

	public void setAssignPatients(final Boolean assignPatients) {
		this.assignPatients = assignPatients;
	}

	@Column(name = "parent_location_id")
	public Integer getParentLocationId() {
		return this.parentLocationId;
	}

	public void setParentLocationId(final Integer parentLocationId) {
		this.parentLocationId = parentLocationId;
	}

	@Column(name = "country_code", length = 32)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(final String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "address_id")
	public Integer getAddressId() {
		return this.addressId;
	}

	public void setAddressId(final Integer addressId) {
		this.addressId = addressId;
	}

}
