package com.covid.model.db;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Medication generated by hbm2java
 */
@Entity
@Table(name = "medication", schema = "release1")
public class Medication implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7149762392314972186L;
	private int medicationId;
	private int patientId;
	private String ingredientCodeSystem;
	private String ingredientConceptCode;
	private String ingredientDescription;
	private String brandedName;
	private Boolean isActive;
	private Integer durationNum;
	private String durationUnits;
	private String strengthNumAndUnits;
	private String doseNumAndUnits;
	private String frequency;
	private String route;
	private String indication;
	private String intentType;
	private String comments;

	public Medication() {
	}

	public Medication(final int medicationId, final int patientId) {
		this.medicationId = medicationId;
		this.patientId = patientId;
	}

	public Medication(final int medicationId, final int patientId, final String ingredientCodeSystem,
			final String ingredientConceptCode, final String ingredientDescription, final String brandedName,
			final Boolean isActive, final Integer durationNum, final String durationUnits,
			final String strengthNumAndUnits, final String doseNumAndUnits, final String frequency, final String route,
			final String indication, final String intentType, final String comments) {
		this.medicationId = medicationId;
		this.patientId = patientId;
		this.ingredientCodeSystem = ingredientCodeSystem;
		this.ingredientConceptCode = ingredientConceptCode;
		this.ingredientDescription = ingredientDescription;
		this.brandedName = brandedName;
		this.isActive = isActive;
		this.durationNum = durationNum;
		this.durationUnits = durationUnits;
		this.strengthNumAndUnits = strengthNumAndUnits;
		this.doseNumAndUnits = doseNumAndUnits;
		this.frequency = frequency;
		this.route = route;
		this.indication = indication;
		this.intentType = intentType;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "medication_id", unique = true, nullable = false)
	public int getMedicationId() {
		return this.medicationId;
	}

	public void setMedicationId(final int medicationId) {
		this.medicationId = medicationId;
	}

	@Column(name = "patient_id", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(final int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "ingredient_code_system", length = 32)
	public String getIngredientCodeSystem() {
		return this.ingredientCodeSystem;
	}

	public void setIngredientCodeSystem(final String ingredientCodeSystem) {
		this.ingredientCodeSystem = ingredientCodeSystem;
	}

	@Column(name = "ingredient_concept_code", length = 32)
	public String getIngredientConceptCode() {
		return this.ingredientConceptCode;
	}

	public void setIngredientConceptCode(final String ingredientConceptCode) {
		this.ingredientConceptCode = ingredientConceptCode;
	}

	@Column(name = "ingredient_description")
	public String getIngredientDescription() {
		return this.ingredientDescription;
	}

	public void setIngredientDescription(final String ingredientDescription) {
		this.ingredientDescription = ingredientDescription;
	}

	@Column(name = "branded_name")
	public String getBrandedName() {
		return this.brandedName;
	}

	public void setBrandedName(final String brandedName) {
		this.brandedName = brandedName;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(final Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "duration_num")
	public Integer getDurationNum() {
		return this.durationNum;
	}

	public void setDurationNum(final Integer durationNum) {
		this.durationNum = durationNum;
	}

	@Column(name = "duration_units", length = 10)
	public String getDurationUnits() {
		return this.durationUnits;
	}

	public void setDurationUnits(final String durationUnits) {
		this.durationUnits = durationUnits;
	}

	@Column(name = "strength_num_and_units", length = 32)
	public String getStrengthNumAndUnits() {
		return this.strengthNumAndUnits;
	}

	public void setStrengthNumAndUnits(final String strengthNumAndUnits) {
		this.strengthNumAndUnits = strengthNumAndUnits;
	}

	@Column(name = "dose_num_and_units", length = 32)
	public String getDoseNumAndUnits() {
		return this.doseNumAndUnits;
	}

	public void setDoseNumAndUnits(final String doseNumAndUnits) {
		this.doseNumAndUnits = doseNumAndUnits;
	}

	@Column(name = "frequency", length = 32)
	public String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(final String frequency) {
		this.frequency = frequency;
	}

	@Column(name = "route", length = 32)
	public String getRoute() {
		return this.route;
	}

	public void setRoute(final String route) {
		this.route = route;
	}

	@Column(name = "indication", length = 32)
	public String getIndication() {
		return this.indication;
	}

	public void setIndication(final String indication) {
		this.indication = indication;
	}

	@Column(name = "intent_type", length = 32)
	public String getIntentType() {
		return this.intentType;
	}

	public void setIntentType(final String intentType) {
		this.intentType = intentType;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(final String comments) {
		this.comments = comments;
	}

}
