package com.covid.model.db;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Patient generated by hbm2java
 */
@Entity
@Table(name = "patient", schema = "release1")
public class Patient implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -8399917459599014679L;
	private int patientId;
	private Integer householdId;
	private Boolean hasPreexistingConditions;
	private Boolean hasMedications;
	private Boolean hasAllergies;
	private Boolean hasAdvanceDirectives;
	private Boolean needsCarer;
	private Boolean hasInternationalTravel;
	private Boolean hasInterstateTravel;
	private Boolean hasHighRiskFacilityVisit;
	private Boolean isHighRiskHealthWorker;
	private String bloodGroup;
	private String clinicalTrialStatus;
	private String comments;

	public Patient() {
	}

	public Patient(final int patientId) {
		this.patientId = patientId;
	}

	public Patient(final int patientId, final Integer householdId, final Boolean hasPreexistingConditions,
			final Boolean hasMedications, final Boolean hasAllergies, final Boolean hasAdvanceDirectives,
			final Boolean needsCarer, final Boolean hasInternationalTravel, final Boolean hasInterstateTravel,
			final Boolean hasHighRiskFacilityVisit, final Boolean isHighRiskHealthWorker, final String bloodGroup,
			final String clinicalTrialStatus, final String comments) {
		this.patientId = patientId;
		this.householdId = householdId;
		this.hasPreexistingConditions = hasPreexistingConditions;
		this.hasMedications = hasMedications;
		this.hasAllergies = hasAllergies;
		this.hasAdvanceDirectives = hasAdvanceDirectives;
		this.needsCarer = needsCarer;
		this.hasInternationalTravel = hasInternationalTravel;
		this.hasInterstateTravel = hasInterstateTravel;
		this.hasHighRiskFacilityVisit = hasHighRiskFacilityVisit;
		this.isHighRiskHealthWorker = isHighRiskHealthWorker;
		this.bloodGroup = bloodGroup;
		this.clinicalTrialStatus = clinicalTrialStatus;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "patient_id", unique = true, nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(final int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "household_id")
	public Integer getHouseholdId() {
		return this.householdId;
	}

	public void setHouseholdId(final Integer householdId) {
		this.householdId = householdId;
	}

	@Column(name = "has_preexisting_conditions")
	public Boolean getHasPreexistingConditions() {
		return this.hasPreexistingConditions;
	}

	public void setHasPreexistingConditions(final Boolean hasPreexistingConditions) {
		this.hasPreexistingConditions = hasPreexistingConditions;
	}

	@Column(name = "has_medications")
	public Boolean getHasMedications() {
		return this.hasMedications;
	}

	public void setHasMedications(final Boolean hasMedications) {
		this.hasMedications = hasMedications;
	}

	@Column(name = "has_allergies")
	public Boolean getHasAllergies() {
		return this.hasAllergies;
	}

	public void setHasAllergies(final Boolean hasAllergies) {
		this.hasAllergies = hasAllergies;
	}

	@Column(name = "has_advance_directives")
	public Boolean getHasAdvanceDirectives() {
		return this.hasAdvanceDirectives;
	}

	public void setHasAdvanceDirectives(final Boolean hasAdvanceDirectives) {
		this.hasAdvanceDirectives = hasAdvanceDirectives;
	}

	@Column(name = "needs_carer")
	public Boolean getNeedsCarer() {
		return this.needsCarer;
	}

	public void setNeedsCarer(final Boolean needsCarer) {
		this.needsCarer = needsCarer;
	}

	@Column(name = "has_international_travel")
	public Boolean getHasInternationalTravel() {
		return this.hasInternationalTravel;
	}

	public void setHasInternationalTravel(final Boolean hasInternationalTravel) {
		this.hasInternationalTravel = hasInternationalTravel;
	}

	@Column(name = "has_interstate_travel")
	public Boolean getHasInterstateTravel() {
		return this.hasInterstateTravel;
	}

	public void setHasInterstateTravel(final Boolean hasInterstateTravel) {
		this.hasInterstateTravel = hasInterstateTravel;
	}

	@Column(name = "has_high_risk_facility_visit")
	public Boolean getHasHighRiskFacilityVisit() {
		return this.hasHighRiskFacilityVisit;
	}

	public void setHasHighRiskFacilityVisit(final Boolean hasHighRiskFacilityVisit) {
		this.hasHighRiskFacilityVisit = hasHighRiskFacilityVisit;
	}

	@Column(name = "is_high_risk_health_worker")
	public Boolean getIsHighRiskHealthWorker() {
		return this.isHighRiskHealthWorker;
	}

	public void setIsHighRiskHealthWorker(final Boolean isHighRiskHealthWorker) {
		this.isHighRiskHealthWorker = isHighRiskHealthWorker;
	}

	@Column(name = "blood_group", length = 32)
	public String getBloodGroup() {
		return this.bloodGroup;
	}

	public void setBloodGroup(final String bloodGroup) {
		this.bloodGroup = bloodGroup;
	}

	@Column(name = "clinical_trial_status", length = 10)
	public String getClinicalTrialStatus() {
		return this.clinicalTrialStatus;
	}

	public void setClinicalTrialStatus(final String clinicalTrialStatus) {
		this.clinicalTrialStatus = clinicalTrialStatus;
	}

	@Column(name = "comments", length = 10)
	public String getComments() {
		return this.comments;
	}

	public void setComments(final String comments) {
		this.comments = comments;
	}

}
