package com.covid.model.db;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PreExistingCondition generated by hbm2java
 */
@Entity
@Table(name = "pre_existing_condition", schema = "release1")
public class PreExistingCondition implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 219262588892203037L;
	private int preExistingConditionId;
	private int patientId;
	private String preExistingConditionCodeSystem;
	private String preExistingCondtionConceptCode;
	private String preExistingCondtionDescription;
	private Boolean isActive;
	private Boolean isControlled;
	private Integer durationNum;
	private String durationUnits;

	public PreExistingCondition() {
	}

	public PreExistingCondition(final int preExistingConditionId, final int patientId) {
		this.preExistingConditionId = preExistingConditionId;
		this.patientId = patientId;
	}

	public PreExistingCondition(final int preExistingConditionId, final int patientId,
			final String preExistingConditionCodeSystem, final String preExistingCondtionConceptCode,
			final String preExistingCondtionDescription, final Boolean isActive, final Boolean isControlled,
			final Integer durationNum, final String durationUnits) {
		this.preExistingConditionId = preExistingConditionId;
		this.patientId = patientId;
		this.preExistingConditionCodeSystem = preExistingConditionCodeSystem;
		this.preExistingCondtionConceptCode = preExistingCondtionConceptCode;
		this.preExistingCondtionDescription = preExistingCondtionDescription;
		this.isActive = isActive;
		this.isControlled = isControlled;
		this.durationNum = durationNum;
		this.durationUnits = durationUnits;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "pre_existing_condition_id", unique = true, nullable = false)
	public int getPreExistingConditionId() {
		return this.preExistingConditionId;
	}

	public void setPreExistingConditionId(final int preExistingConditionId) {
		this.preExistingConditionId = preExistingConditionId;
	}

	@Column(name = "patient_id", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(final int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "pre_existing_condition_code_system", length = 32)
	public String getPreExistingConditionCodeSystem() {
		return this.preExistingConditionCodeSystem;
	}

	public void setPreExistingConditionCodeSystem(final String preExistingConditionCodeSystem) {
		this.preExistingConditionCodeSystem = preExistingConditionCodeSystem;
	}

	@Column(name = "pre_existing_condtion_concept_code", length = 32)
	public String getPreExistingCondtionConceptCode() {
		return this.preExistingCondtionConceptCode;
	}

	public void setPreExistingCondtionConceptCode(final String preExistingCondtionConceptCode) {
		this.preExistingCondtionConceptCode = preExistingCondtionConceptCode;
	}

	@Column(name = "pre_existing_condtion_description")
	public String getPreExistingCondtionDescription() {
		return this.preExistingCondtionDescription;
	}

	public void setPreExistingCondtionDescription(final String preExistingCondtionDescription) {
		this.preExistingCondtionDescription = preExistingCondtionDescription;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(final Boolean isActive) {
		this.isActive = isActive;
	}

	@Column(name = "is_controlled")
	public Boolean getIsControlled() {
		return this.isControlled;
	}

	public void setIsControlled(final Boolean isControlled) {
		this.isControlled = isControlled;
	}

	@Column(name = "duration_num")
	public Integer getDurationNum() {
		return this.durationNum;
	}

	public void setDurationNum(final Integer durationNum) {
		this.durationNum = durationNum;
	}

	@Column(name = "duration_units", length = 10)
	public String getDurationUnits() {
		return this.durationUnits;
	}

	public void setDurationUnits(final String durationUnits) {
		this.durationUnits = durationUnits;
	}

}
