INSERT INTO public."LocationHierarchy"("LocationId", "LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode") OVERRIDING SYSTEM VALUE VALUES(0,'[Select a country]','0','false',0,'0');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Andorra','AD','false',0,'AD');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('United Arab Emirates','AE','false',0,'AE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Afghanistan','AF','false',0,'AF');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Antigua and Barbuda','AG','false',0,'AG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Anguilla','AI','false',0,'AI');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Albania','AL','false',0,'AL');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Armenia','AM','false',0,'AM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Angola','AO','false',0,'AO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Antarctica','AQ','false',0,'AQ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Argentina','AR','false',0,'AR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('American Samoa','AS','false',0,'AS');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Austria','AT','false',0,'AT');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Australia','AU','false',0,'AU');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Aruba','AW','false',0,'AW');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Åland Islands','AX','false',0,'AX');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Azerbaijan','AZ','false',0,'AZ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bosnia and Herzegovina','BA','false',0,'BA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Barbados','BB','false',0,'BB');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bangladesh','BD','false',0,'BD');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Belgium','BE','false',0,'BE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Burkina Faso','BF','false',0,'BF');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bulgaria','BG','false',0,'BG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bahrain','BH','false',0,'BH');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Burundi','BI','false',0,'BI');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Benin','BJ','false',0,'BJ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Saint BarthÃ©lemy','BL','false',0,'BL');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bermuda','BM','false',0,'BM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Brunei Darussalam','BN','false',0,'BN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bolivia (Plurinational State of)','BO','false',0,'BO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bonaire, Sint Eustatius and Saba','BQ','false',0,'BQ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Brazil','BR','false',0,'BR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bahamas','BS','false',0,'BS');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bhutan','BT','false',0,'BT');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bouvet Island','BV','false',0,'BV');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Botswana','BW','false',0,'BW');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Belarus','BY','false',0,'BY');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Belize','BZ','false',0,'BZ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Canada','CA','false',0,'CA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Cocos (Keeling) Islands','CC','false',0,'CC');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Congo, Democratic Republic of the','CD','false',0,'CD');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Central African Republic','CF','false',0,'CF');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Congo','CG','false',0,'CG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Switzerland','CH','false',0,'CH');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('CÃ´te d''Ivoire','CI','false',0,'CI');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Cook Islands','CK','false',0,'CK');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Chile','CL','false',0,'CL');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Cameroon','CM','false',0,'CM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('China','CN','false',0,'CN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Colombia','CO','false',0,'CO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Costa Rica','CR','false',0,'CR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Cuba','CU','false',0,'CU');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Cabo Verde','CV','false',0,'CV');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('CuraÃ§ao','CW','false',0,'CW');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Christmas Island','CX','false',0,'CX');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Cyprus','CY','false',0,'CY');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Czechia','CZ','false',0,'CZ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Germany','DE','false',0,'DE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Djibouti','DJ','false',0,'DJ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Denmark','DK','false',0,'DK');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Dominica','DM','false',0,'DM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Dominican Republic','DO','false',0,'DO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Algeria','DZ','false',0,'DZ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Ecuador','EC','false',0,'EC');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Estonia','EE','false',0,'EE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Egypt','EG','false',0,'EG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Western Sahara','EH','false',0,'EH');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Eritrea','ER','false',0,'ER');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Spain','ES','false',0,'ES');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Ethiopia','ET','false',0,'ET');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Finland','FI','false',0,'FI');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Fiji','FJ','false',0,'FJ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Falkland Islands (Malvinas)','FK','false',0,'FK');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Micronesia (Federated States of)','FM','false',0,'FM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Faroe Islands','FO','false',0,'FO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('France','FR','false',0,'FR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Gabon','GA','false',0,'GA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('United Kingdom of Great Britain and Northern Ireland','GB','false',0,'GB');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Grenada','GD','false',0,'GD');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Georgia','GE','false',0,'GE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('French Guiana','GF','false',0,'GF');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Guernsey','GG','false',0,'GG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Ghana','GH','false',0,'GH');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Gibraltar','GI','false',0,'GI');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Greenland','GL','false',0,'GL');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Gambia','GM','false',0,'GM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Guinea','GN','false',0,'GN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Guadeloupe','GP','false',0,'GP');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Equatorial Guinea','GQ','false',0,'GQ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Greece','GR','false',0,'GR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('South Georgia and the South Sandwich Islands','GS','false',0,'GS');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Guatemala','GT','false',0,'GT');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Guam','GU','false',0,'GU');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Guinea-Bissau','GW','false',0,'GW');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Guyana','GY','false',0,'GY');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Hong Kong','HK','false',0,'HK');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Heard Island and McDonald Islands','HM','false',0,'HM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Honduras','HN','false',0,'HN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Croatia','HR','false',0,'HR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Haiti','HT','false',0,'HT');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Hungary','HU','false',0,'HU');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Indonesia','ID','false',0,'ID');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Ireland','IE','false',0,'IE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Israel','IL','false',0,'IL');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Isle of Man','IM','false',0,'IM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('India','IN','false',0,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('British Indian Ocean Territory','IO','false',0,'IO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Iraq','IQ','false',0,'IQ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Iran (Islamic Republic of)','IR','false',0,'IR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Iceland','IS','false',0,'IS');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Italy','IT','false',0,'IT');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Jersey','JE','false',0,'JE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Jamaica','JM','false',0,'JM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Jordan','JO','false',0,'JO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Japan','JP','false',0,'JP');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Kenya','KE','false',0,'KE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Kyrgyzstan','KG','false',0,'KG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Cambodia','KH','false',0,'KH');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Kiribati','KI','false',0,'KI');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Comoros','KM','false',0,'KM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Saint Kitts and Nevis','KN','false',0,'KN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Korea (Democratic People''s Republic of)','KP','false',0,'KP');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Korea, Republic of','KR','false',0,'KR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Kuwait','KW','false',0,'KW');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Cayman Islands','KY','false',0,'KY');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Kazakhstan','KZ','false',0,'KZ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Lao People''s Democratic Republic','LA','false',0,'LA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Lebanon','LB','false',0,'LB');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Saint Lucia','LC','false',0,'LC');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Liechtenstein','LI','false',0,'LI');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Sri Lanka','LK','false',0,'LK');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Liberia','LR','false',0,'LR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Lesotho','LS','false',0,'LS');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Lithuania','LT','false',0,'LT');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Luxembourg','LU','false',0,'LU');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Latvia','LV','false',0,'LV');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Libya','LY','false',0,'LY');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Morocco','MA','false',0,'MA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Monaco','MC','false',0,'MC');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Moldova, Republic of','MD','false',0,'MD');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Montenegro','ME','false',0,'ME');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Saint Martin (French part)','MF','false',0,'MF');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Madagascar','MG','false',0,'MG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Marshall Islands','MH','false',0,'MH');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('North Macedonia','MK','false',0,'MK');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Mali','ML','false',0,'ML');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Myanmar','MM','false',0,'MM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Mongolia','MN','false',0,'MN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Macao','MO','false',0,'MO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Northern Mariana Islands','MP','false',0,'MP');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Martinique','MQ','false',0,'MQ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Mauritania','MR','false',0,'MR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Montserrat','MS','false',0,'MS');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Malta','MT','false',0,'MT');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Mauritius','MU','false',0,'MU');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Maldives','MV','false',0,'MV');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Malawi','MW','false',0,'MW');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Mexico','MX','false',0,'MX');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Malaysia','MY','false',0,'MY');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Mozambique','MZ','false',0,'MZ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Namibia','NA','false',0,'NA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('New Caledonia','NC','false',0,'NC');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Niger','NE','false',0,'NE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Norfolk Island','NF','false',0,'NF');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Nigeria','NG','false',0,'NG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Nicaragua','NI','false',0,'NI');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Netherlands','NL','false',0,'NL');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Norway','NO','false',0,'NO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Nepal','NP','false',0,'NP');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Nauru','NR','false',0,'NR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Niue','NU','false',0,'NU');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('New Zealand','NZ','false',0,'NZ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Oman','OM','false',0,'OM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Panama','PA','false',0,'PA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Peru','PE','false',0,'PE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('French Polynesia','PF','false',0,'PF');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Papua New Guinea','PG','false',0,'PG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Philippines','PH','false',0,'PH');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Pakistan','PK','false',0,'PK');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Poland','PL','false',0,'PL');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Saint Pierre and Miquelon','PM','false',0,'PM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Pitcairn','PN','false',0,'PN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Puerto Rico','PR','false',0,'PR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Palestine, State of','PS','false',0,'PS');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Portugal','PT','false',0,'PT');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Palau','PW','false',0,'PW');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Paraguay','PY','false',0,'PY');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Qatar','QA','false',0,'QA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('RÃ©union','RE','false',0,'RE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Romania','RO','false',0,'RO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Serbia','RS','false',0,'RS');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Russian Federation','RU','false',0,'RU');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Rwanda','RW','false',0,'RW');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Saudi Arabia','SA','false',0,'SA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Solomon Islands','SB','false',0,'SB');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Seychelles','SC','false',0,'SC');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Sudan','SD','false',0,'SD');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Sweden','SE','false',0,'SE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Singapore','SG','false',0,'SG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Saint Helena, Ascension and Tristan da Cunha','SH','false',0,'SH');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Slovenia','SI','false',0,'SI');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Svalbard and Jan Mayen','SJ','false',0,'SJ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Slovakia','SK','false',0,'SK');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Sierra Leone','SL','false',0,'SL');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('San Marino','SM','false',0,'SM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Senegal','SN','false',0,'SN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Somalia','SO','false',0,'SO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Suriname','SR','false',0,'SR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('South Sudan','SS','false',0,'SS');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Sao Tome and Principe','ST','false',0,'ST');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('El Salvador','SV','false',0,'SV');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Sint Maarten (Dutch part)','SX','false',0,'SX');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Syrian Arab Republic','SY','false',0,'SY');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Eswatini','SZ','false',0,'SZ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Turks and Caicos Islands','TC','false',0,'TC');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Chad','TD','false',0,'TD');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('French Southern Territories','TF','false',0,'TF');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Togo','TG','false',0,'TG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Thailand','TH','false',0,'TH');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tajikistan','TJ','false',0,'TJ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tokelau','TK','false',0,'TK');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Timor-Leste','TL','false',0,'TL');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Turkmenistan','TM','false',0,'TM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tunisia','TN','false',0,'TN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tonga','TO','false',0,'TO');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Turkey','TR','false',0,'TR');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Trinidad and Tobago','TT','false',0,'TT');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tuvalu','TV','false',0,'TV');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Taiwan, Province of China','TW','false',0,'TW');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tanzania, United Republic of','TZ','false',0,'TZ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Ukraine','UA','false',0,'UA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Uganda','UG','false',0,'UG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('United States Minor Outlying Islands','UM','false',0,'UM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('United States of America','US','false',0,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Uruguay','UY','false',0,'UY');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Uzbekistan','UZ','false',0,'UZ');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Holy See','VA','false',0,'VA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Saint Vincent and the Grenadines','VC','false',0,'VC');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Venezuela (Bolivarian Republic of)','VE','false',0,'VE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Virgin Islands (British)','VG','false',0,'VG');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Virgin Islands (U.S.)','VI','false',0,'VI');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Viet Nam','VN','false',0,'VN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Vanuatu','VU','false',0,'VU');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Wallis and Futuna','WF','false',0,'WF');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Samoa','WS','false',0,'WS');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Yemen','YE','false',0,'YE');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Mayotte','YT','false',0,'YT');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('South Africa','ZA','false',0,'ZA');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Zambia','ZM','false',0,'ZM');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Zimbabwe','ZW','false',0,'ZW');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Andaman and Nicobar Islands','IN-AN','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Andhra Pradesh','IN-AP','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Arunachal Pradesh','IN-AR','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Assam','IN-AS','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Bihar','IN-BR','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Chandigarh','IN-CH','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Chhattisgarh','IN-CT','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Dadra and Nagar Haveli','IN-DN','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Daman and Diu','IN-DD','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Delhi','IN-DL','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Goa','IN-GA','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Gujarat','IN-GJ','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Haryana','IN-HR','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Himachal Pradesh','IN-HP','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Jammu and Kashmir','IN-JK','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Jharkhand','IN-JH','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Karnataka','IN-KA','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Kerala','IN-KL','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Madhya Pradesh','IN-MP','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Maharashtra','IN-MH','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Manipur','IN-MN','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Meghalaya','IN-ML','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Mizoram','IN-MZ','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Nagaland','IN-NL','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Odisha','IN-OR','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Puducherry','IN-PY','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Punjab','IN-PB','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Rajasthan','IN-RJ','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Sikkim','IN-SK','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tamil Nadu','IN-TN','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Telangana','IN-TG','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tripura','IN-TR','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Uttar Pradesh','IN-UP','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Uttarakhand','IN-UT','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('West Bengal','IN-WB','false',105,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Alabama','US-AL','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Alaska','US-AK','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Arizona','US-AZ','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Arkansas','US-AR','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('California','US-CA','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Colorado','US-CO','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Connecticut','US-CT','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Delaware','US-DE','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('District of Columbia','US-DC','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Florida','US-FL','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Georgia','US-GA','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Hawaii','US-HI','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Idaho','US-ID','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Illinois','US-IL','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Indiana','US-IN','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Iowa','US-IA','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Kansas','US-KS','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Kentucky','US-KY','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Louisiana','US-LA','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Maine','US-ME','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Maryland','US-MD','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Massachusetts','US-MA','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Michigan','US-MI','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Minnesota','US-MN','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Mississippi','US-MS','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Missouri','US-MO','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Montana','US-MT','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Nebraska','US-NE','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Nevada','US-NV','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('New Hampshire','US-NH','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('New Jersey','US-NJ','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('New Mexico','US-NM','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('New York','US-NY','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('North Carolina','US-NC','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('North Dakota','US-ND','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Ohio','US-OH','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Oklahoma','US-OK','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Oregon','US-OR','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Pennsylvania','US-PA','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Rhode Island','US-RI','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('South Carolina','US-SC','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('South Dakota','US-SD','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tennessee','US-TN','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Texas','US-TX','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Utah','US-UT','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Vermont','US-VT','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Virginia','US-VA','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Washington','US-WA','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('West Virginia','US-WV','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Wisconsin','US-WI','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Wyoming','US-WY','false',233,'US');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Madurai District','IN-TN-MDU','false',279,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Madurai Taluk','IN-TN-MDU','false',336,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Madurai City','IN-TN-MDU','true',337,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Chengalpattu District','IN-TN-CGL','false',279,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Chengalpattu Taluk','IN-TN-CGL','false',339,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Chengalpattu','IN-TN-CGL','true',340,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tiruvannamalai District','IN-TN-TV','false',279,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tiruvannamalai Taluk','IN-TN-TV','false',341,'IN');
INSERT INTO public."LocationHierarchy"("LocationName", "LocationAbbreviation", "AssignPatients", "ParentLocationId", "CountryCode")VALUES('Tiruvannamalai','IN-TN-TV','true',342,'IN');

