package com.covid.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * CovidContact generated by hbm2java
 */
@Entity
@Table(name = "covid_contact", schema = "release1")
public class CovidContact implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 3576655729741644430L;
	private int contactId;
	private int contactUserId1;
	private int contactUserId2;
	private Date contactTimeStart;
	private Date contactTimeEnd;
	private Integer contactLocationId;
	private String contactRelationship;
	private String contactExposure;

	public CovidContact() {
	}

	public CovidContact(final int contactId, final int contactUserId1, final int contactUserId2) {
		this.contactId = contactId;
		this.contactUserId1 = contactUserId1;
		this.contactUserId2 = contactUserId2;
	}

	public CovidContact(final int contactId, final int contactUserId1, final int contactUserId2,
			final Date contactTimeStart, final Date contactTimeEnd, final Integer contactLocationId,
			final String contactRelationship, final String contactExposure) {
		this.contactId = contactId;
		this.contactUserId1 = contactUserId1;
		this.contactUserId2 = contactUserId2;
		this.contactTimeStart = contactTimeStart;
		this.contactTimeEnd = contactTimeEnd;
		this.contactLocationId = contactLocationId;
		this.contactRelationship = contactRelationship;
		this.contactExposure = contactExposure;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "contact_id", unique = true, nullable = false)
	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(final int contactId) {
		this.contactId = contactId;
	}

	@Column(name = "contact_user_id_1", nullable = false)
	public int getContactUserId1() {
		return this.contactUserId1;
	}

	public void setContactUserId1(final int contactUserId1) {
		this.contactUserId1 = contactUserId1;
	}

	@Column(name = "contact_user_id_2", nullable = false)
	public int getContactUserId2() {
		return this.contactUserId2;
	}

	public void setContactUserId2(final int contactUserId2) {
		this.contactUserId2 = contactUserId2;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "contact_time_start", length = 29)
	public Date getContactTimeStart() {
		return this.contactTimeStart;
	}

	public void setContactTimeStart(final Date contactTimeStart) {
		this.contactTimeStart = contactTimeStart;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "contact_time_end", length = 29)
	public Date getContactTimeEnd() {
		return this.contactTimeEnd;
	}

	public void setContactTimeEnd(final Date contactTimeEnd) {
		this.contactTimeEnd = contactTimeEnd;
	}

	@Column(name = "contact_location_id")
	public Integer getContactLocationId() {
		return this.contactLocationId;
	}

	public void setContactLocationId(final Integer contactLocationId) {
		this.contactLocationId = contactLocationId;
	}

	@Column(name = "contact_relationship", length = 10)
	public String getContactRelationship() {
		return this.contactRelationship;
	}

	public void setContactRelationship(final String contactRelationship) {
		this.contactRelationship = contactRelationship;
	}

	@Column(name = "contact_exposure", length = 10)
	public String getContactExposure() {
		return this.contactExposure;
	}

	public void setContactExposure(final String contactExposure) {
		this.contactExposure = contactExposure;
	}

}
