package com.covid.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmailAddress generated by hbm2java
 */
@Entity
@Table(name = "email_address", schema = "release1")
public class EmailAddress implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -1441787957545655608L;
	private int emailAddressId;
	private int userId;
	private String emailAddress;
	private String emailAddressType;
	private Boolean isPreferred;
	private Boolean isPrimaryUser;
	private Integer primaryUserId;

	public EmailAddress() {
	}

	public EmailAddress(final int emailAddressId, final int userId, final String emailAddress,
			final String emailAddressType) {
		this.emailAddressId = emailAddressId;
		this.userId = userId;
		this.emailAddress = emailAddress;
		this.emailAddressType = emailAddressType;
	}

	public EmailAddress(final int emailAddressId, final int userId, final String emailAddress,
			final String emailAddressType, final Boolean isPreferred, final Boolean isPrimaryUser,
			final Integer primaryUserId) {
		this.emailAddressId = emailAddressId;
		this.userId = userId;
		this.emailAddress = emailAddress;
		this.emailAddressType = emailAddressType;
		this.isPreferred = isPreferred;
		this.isPrimaryUser = isPrimaryUser;
		this.primaryUserId = primaryUserId;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "email_address_id", unique = true, nullable = false)
	public int getEmailAddressId() {
		return this.emailAddressId;
	}

	public void setEmailAddressId(final int emailAddressId) {
		this.emailAddressId = emailAddressId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(final int userId) {
		this.userId = userId;
	}

	@Column(name = "email_address", nullable = false, length = 64)
	public String getEmailAddress() {
		return this.emailAddress;
	}

	public void setEmailAddress(final String emailAddress) {
		this.emailAddress = emailAddress;
	}

	@Column(name = "email_address_type", nullable = false, length = 32)
	public String getEmailAddressType() {
		return this.emailAddressType;
	}

	public void setEmailAddressType(final String emailAddressType) {
		this.emailAddressType = emailAddressType;
	}

	@Column(name = "is_preferred")
	public Boolean getIsPreferred() {
		return this.isPreferred;
	}

	public void setIsPreferred(final Boolean isPreferred) {
		this.isPreferred = isPreferred;
	}

	@Column(name = "is_primary_user")
	public Boolean getIsPrimaryUser() {
		return this.isPrimaryUser;
	}

	public void setIsPrimaryUser(final Boolean isPrimaryUser) {
		this.isPrimaryUser = isPrimaryUser;
	}

	@Column(name = "primary_user_id")
	public Integer getPrimaryUserId() {
		return this.primaryUserId;
	}

	public void setPrimaryUserId(final Integer primaryUserId) {
		this.primaryUserId = primaryUserId;
	}

}
