package com.covid.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExternalIdentifier generated by hbm2java
 */
@Entity
@Table(name = "external_identifier", schema = "release1")
public class ExternalIdentifier implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 7091940679786083913L;
	private int identificationId;
	private Integer userId;
	private String idType;
	private String idTypeUri;
	private String issuingAuthorityName;
	private String issuingAuthorityId;
	private String issuingAuthorityUri;
	private String idNumber;
	private String issueDate;
	private String expiryDate;

	public ExternalIdentifier() {
	}

	public ExternalIdentifier(final int identificationId) {
		this.identificationId = identificationId;
	}

	public ExternalIdentifier(final int identificationId, final Integer userId, final String idType,
			final String idTypeUri, final String issuingAuthorityName, final String issuingAuthorityId,
			final String issuingAuthorityUri, final String idNumber, final String issueDate, final String expiryDate) {
		this.identificationId = identificationId;
		this.userId = userId;
		this.idType = idType;
		this.idTypeUri = idTypeUri;
		this.issuingAuthorityName = issuingAuthorityName;
		this.issuingAuthorityId = issuingAuthorityId;
		this.issuingAuthorityUri = issuingAuthorityUri;
		this.idNumber = idNumber;
		this.issueDate = issueDate;
		this.expiryDate = expiryDate;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "identification_id", unique = true, nullable = false)
	public int getIdentificationId() {
		return this.identificationId;
	}

	public void setIdentificationId(final int identificationId) {
		this.identificationId = identificationId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(final Integer userId) {
		this.userId = userId;
	}

	@Column(name = "id_type", length = 32)
	public String getIdType() {
		return this.idType;
	}

	public void setIdType(final String idType) {
		this.idType = idType;
	}

	@Column(name = "id_type_uri", length = 10)
	public String getIdTypeUri() {
		return this.idTypeUri;
	}

	public void setIdTypeUri(final String idTypeUri) {
		this.idTypeUri = idTypeUri;
	}

	@Column(name = "issuing_authority_name", length = 10)
	public String getIssuingAuthorityName() {
		return this.issuingAuthorityName;
	}

	public void setIssuingAuthorityName(final String issuingAuthorityName) {
		this.issuingAuthorityName = issuingAuthorityName;
	}

	@Column(name = "issuing_authority_id", length = 10)
	public String getIssuingAuthorityId() {
		return this.issuingAuthorityId;
	}

	public void setIssuingAuthorityId(final String issuingAuthorityId) {
		this.issuingAuthorityId = issuingAuthorityId;
	}

	@Column(name = "issuing_authority_uri", length = 10)
	public String getIssuingAuthorityUri() {
		return this.issuingAuthorityUri;
	}

	public void setIssuingAuthorityUri(final String issuingAuthorityUri) {
		this.issuingAuthorityUri = issuingAuthorityUri;
	}

	@Column(name = "id_number", length = 20)
	public String getIdNumber() {
		return this.idNumber;
	}

	public void setIdNumber(final String idNumber) {
		this.idNumber = idNumber;
	}

	@Column(name = "issue_date", length = 10)
	public String getIssueDate() {
		return this.issueDate;
	}

	public void setIssueDate(final String issueDate) {
		this.issueDate = issueDate;
	}

	@Column(name = "expiry_date", length = 10)
	public String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(final String expiryDate) {
		this.expiryDate = expiryDate;
	}

}
