package com.covid.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientRequestHistory generated by hbm2java
 */
@Entity
@Table(name = "patient_request_history", schema = "release1")
public class PatientRequestHistory implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -7599200919649682882L;
	private int patientRequestHistoryId;
	private int patientId;
	private String requestType;
	private Date requestDateTime;
	private String requestStatus;
	private String requestComments;
	private String responseType;
	private Integer responseUserId;
	private Date responseDateTime;
	private String responseComments;

	public PatientRequestHistory() {
	}

	public PatientRequestHistory(final int patientRequestHistoryId, final int patientId) {
		this.patientRequestHistoryId = patientRequestHistoryId;
		this.patientId = patientId;
	}

	public PatientRequestHistory(final int patientRequestHistoryId, final int patientId, final String requestType,
			final Date requestDateTime, final String requestStatus, final String requestComments,
			final String responseType, final Integer responseUserId, final Date responseDateTime,
			final String responseComments) {
		this.patientRequestHistoryId = patientRequestHistoryId;
		this.patientId = patientId;
		this.requestType = requestType;
		this.requestDateTime = requestDateTime;
		this.requestStatus = requestStatus;
		this.requestComments = requestComments;
		this.responseType = responseType;
		this.responseUserId = responseUserId;
		this.responseDateTime = responseDateTime;
		this.responseComments = responseComments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "patient_request_history_id", unique = true, nullable = false)
	public int getPatientRequestHistoryId() {
		return this.patientRequestHistoryId;
	}

	public void setPatientRequestHistoryId(final int patientRequestHistoryId) {
		this.patientRequestHistoryId = patientRequestHistoryId;
	}

	@Column(name = "patient_id", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(final int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "request_type", length = 16)
	public String getRequestType() {
		return this.requestType;
	}

	public void setRequestType(final String requestType) {
		this.requestType = requestType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "request_date_time", length = 29)
	public Date getRequestDateTime() {
		return this.requestDateTime;
	}

	public void setRequestDateTime(final Date requestDateTime) {
		this.requestDateTime = requestDateTime;
	}

	@Column(name = "request_status")
	public String getRequestStatus() {
		return this.requestStatus;
	}

	public void setRequestStatus(final String requestStatus) {
		this.requestStatus = requestStatus;
	}

	@Column(name = "request_comments")
	public String getRequestComments() {
		return this.requestComments;
	}

	public void setRequestComments(final String requestComments) {
		this.requestComments = requestComments;
	}

	@Column(name = "response_type", length = 16)
	public String getResponseType() {
		return this.responseType;
	}

	public void setResponseType(final String responseType) {
		this.responseType = responseType;
	}

	@Column(name = "response_user_id")
	public Integer getResponseUserId() {
		return this.responseUserId;
	}

	public void setResponseUserId(final Integer responseUserId) {
		this.responseUserId = responseUserId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "response_date_time", length = 29)
	public Date getResponseDateTime() {
		return this.responseDateTime;
	}

	public void setResponseDateTime(final Date responseDateTime) {
		this.responseDateTime = responseDateTime;
	}

	@Column(name = "response_comments")
	public String getResponseComments() {
		return this.responseComments;
	}

	public void setResponseComments(final String responseComments) {
		this.responseComments = responseComments;
	}

}
