package com.covid.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * PatientStatus generated by hbm2java
 */
@Entity
@Table(name = "patient_status", schema = "release1")
public class PatientStatus implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 5123166360650632641L;
	private int patientStatusId;
	private int patientId;
	private String covid19Status;
	private String healthStatus;
	private String quarIsltStatus;
	private Date quarIsltStartDateTime;
	private Date quarIsltEndDateTime;
	private String quarIsltRequestStatus;
	private String medicalRequestStatus;
	private String suppliesRequestStatus;
	private String geofenceStatus;
	private String appHeartbeatStatus;
	private Date updatedDateTime;
	private BigDecimal latitude;
	private BigDecimal longitude;
	private String comments;

	public PatientStatus() {
	}

	public PatientStatus(final int patientStatusId, final int patientId) {
		this.patientStatusId = patientStatusId;
		this.patientId = patientId;
	}

	public PatientStatus(final int patientStatusId, final int patientId, final String covid19Status,
			final String healthStatus, final String quarIsltStatus, final Date quarIsltStartDateTime,
			final Date quarIsltEndDateTime, final String quarIsltRequestStatus, final String medicalRequestStatus,
			final String suppliesRequestStatus, final String geofenceStatus, final String appHeartbeatStatus,
			final Date updatedDateTime, final BigDecimal latitude, final BigDecimal longitude, final String comments) {
		this.patientStatusId = patientStatusId;
		this.patientId = patientId;
		this.covid19Status = covid19Status;
		this.healthStatus = healthStatus;
		this.quarIsltStatus = quarIsltStatus;
		this.quarIsltStartDateTime = quarIsltStartDateTime;
		this.quarIsltEndDateTime = quarIsltEndDateTime;
		this.quarIsltRequestStatus = quarIsltRequestStatus;
		this.medicalRequestStatus = medicalRequestStatus;
		this.suppliesRequestStatus = suppliesRequestStatus;
		this.geofenceStatus = geofenceStatus;
		this.appHeartbeatStatus = appHeartbeatStatus;
		this.updatedDateTime = updatedDateTime;
		this.latitude = latitude;
		this.longitude = longitude;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "patient_status_id", unique = true, nullable = false)
	public int getPatientStatusId() {
		return this.patientStatusId;
	}

	public void setPatientStatusId(final int patientStatusId) {
		this.patientStatusId = patientStatusId;
	}

	@Column(name = "patient_id", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(final int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "covid19_status", length = 32)
	public String getCovid19Status() {
		return this.covid19Status;
	}

	public void setCovid19Status(final String covid19Status) {
		this.covid19Status = covid19Status;
	}

	@Column(name = "health_status", length = 32)
	public String getHealthStatus() {
		return this.healthStatus;
	}

	public void setHealthStatus(final String healthStatus) {
		this.healthStatus = healthStatus;
	}

	@Column(name = "quar_islt_status", length = 32)
	public String getQuarIsltStatus() {
		return this.quarIsltStatus;
	}

	public void setQuarIsltStatus(final String quarIsltStatus) {
		this.quarIsltStatus = quarIsltStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quar_islt_start_date_time", length = 29)
	public Date getQuarIsltStartDateTime() {
		return this.quarIsltStartDateTime;
	}

	public void setQuarIsltStartDateTime(final Date quarIsltStartDateTime) {
		this.quarIsltStartDateTime = quarIsltStartDateTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "quar_islt_end_date_time", length = 29)
	public Date getQuarIsltEndDateTime() {
		return this.quarIsltEndDateTime;
	}

	public void setQuarIsltEndDateTime(final Date quarIsltEndDateTime) {
		this.quarIsltEndDateTime = quarIsltEndDateTime;
	}

	@Column(name = "quar_islt_request_status", length = 32)
	public String getQuarIsltRequestStatus() {
		return this.quarIsltRequestStatus;
	}

	public void setQuarIsltRequestStatus(final String quarIsltRequestStatus) {
		this.quarIsltRequestStatus = quarIsltRequestStatus;
	}

	@Column(name = "medical_request_status", length = 32)
	public String getMedicalRequestStatus() {
		return this.medicalRequestStatus;
	}

	public void setMedicalRequestStatus(final String medicalRequestStatus) {
		this.medicalRequestStatus = medicalRequestStatus;
	}

	@Column(name = "supplies_request_status", length = 32)
	public String getSuppliesRequestStatus() {
		return this.suppliesRequestStatus;
	}

	public void setSuppliesRequestStatus(final String suppliesRequestStatus) {
		this.suppliesRequestStatus = suppliesRequestStatus;
	}

	@Column(name = "geofence_status", length = 16)
	public String getGeofenceStatus() {
		return this.geofenceStatus;
	}

	public void setGeofenceStatus(final String geofenceStatus) {
		this.geofenceStatus = geofenceStatus;
	}

	@Column(name = "app_heartbeat_status", length = 16)
	public String getAppHeartbeatStatus() {
		return this.appHeartbeatStatus;
	}

	public void setAppHeartbeatStatus(final String appHeartbeatStatus) {
		this.appHeartbeatStatus = appHeartbeatStatus;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "updated_date_time", length = 29)
	public Date getUpdatedDateTime() {
		return this.updatedDateTime;
	}

	public void setUpdatedDateTime(final Date updatedDateTime) {
		this.updatedDateTime = updatedDateTime;
	}

	@Column(name = "latitude", precision = 10, scale = 8)
	public BigDecimal getLatitude() {
		return this.latitude;
	}

	public void setLatitude(final BigDecimal latitude) {
		this.latitude = latitude;
	}

	@Column(name = "longitude", precision = 11, scale = 8)
	public BigDecimal getLongitude() {
		return this.longitude;
	}

	public void setLongitude(final BigDecimal longitude) {
		this.longitude = longitude;
	}

	@Column(name = "comments", length = 128)
	public String getComments() {
		return this.comments;
	}

	public void setComments(final String comments) {
		this.comments = comments;
	}

}
