package com.covid.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PhoneNumber generated by hbm2java
 */
@Entity
@Table(name = "phone_number", schema = "release1")
public class PhoneNumber implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 5437513907310793500L;
	private int phoneNumberId;
	private int userId;
	private String phoneType;
	private String phoneNumber;
	private String phoneNumberExtn;
	private String phoneNumberFormatted;
	private Boolean isPreferred;
	private Boolean isPrimaryUser;
	private Integer primaryUserId;
	private Boolean hasInternetAccess;
	private Boolean hasSmsaccess;
	private Boolean hasWhatsappAccess;
	private Boolean hasTelegramAccess;
	private Boolean providesLocation;

	public PhoneNumber() {
	}

	public PhoneNumber(final int phoneNumberId, final int userId, final String phoneType) {
		this.phoneNumberId = phoneNumberId;
		this.userId = userId;
		this.phoneType = phoneType;
	}

	public PhoneNumber(final int phoneNumberId, final int userId, final String phoneType, final String phoneNumber,
			final String phoneNumberExtn, final String phoneNumberFormatted, final Boolean isPreferred,
			final Boolean isPrimaryUser, final Integer primaryUserId, final Boolean hasInternetAccess,
			final Boolean hasSmsaccess, final Boolean hasWhatsappAccess, final Boolean hasTelegramAccess,
			final Boolean providesLocation) {
		this.phoneNumberId = phoneNumberId;
		this.userId = userId;
		this.phoneType = phoneType;
		this.phoneNumber = phoneNumber;
		this.phoneNumberExtn = phoneNumberExtn;
		this.phoneNumberFormatted = phoneNumberFormatted;
		this.isPreferred = isPreferred;
		this.isPrimaryUser = isPrimaryUser;
		this.primaryUserId = primaryUserId;
		this.hasInternetAccess = hasInternetAccess;
		this.hasSmsaccess = hasSmsaccess;
		this.hasWhatsappAccess = hasWhatsappAccess;
		this.hasTelegramAccess = hasTelegramAccess;
		this.providesLocation = providesLocation;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "phone_number_id", unique = true, nullable = false)
	public int getPhoneNumberId() {
		return this.phoneNumberId;
	}

	public void setPhoneNumberId(final int phoneNumberId) {
		this.phoneNumberId = phoneNumberId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(final int userId) {
		this.userId = userId;
	}

	@Column(name = "phone_type", nullable = false, length = 32)
	public String getPhoneType() {
		return this.phoneType;
	}

	public void setPhoneType(final String phoneType) {
		this.phoneType = phoneType;
	}

	@Column(name = "phone_number", length = 20)
	public String getPhoneNumber() {
		return this.phoneNumber;
	}

	public void setPhoneNumber(final String phoneNumber) {
		this.phoneNumber = phoneNumber;
	}

	@Column(name = "phone_number_extn", length = 8)
	public String getPhoneNumberExtn() {
		return this.phoneNumberExtn;
	}

	public void setPhoneNumberExtn(final String phoneNumberExtn) {
		this.phoneNumberExtn = phoneNumberExtn;
	}

	@Column(name = "phone_number_formatted", length = 32)
	public String getPhoneNumberFormatted() {
		return this.phoneNumberFormatted;
	}

	public void setPhoneNumberFormatted(final String phoneNumberFormatted) {
		this.phoneNumberFormatted = phoneNumberFormatted;
	}

	@Column(name = "is_preferred")
	public Boolean getIsPreferred() {
		return this.isPreferred;
	}

	public void setIsPreferred(final Boolean isPreferred) {
		this.isPreferred = isPreferred;
	}

	@Column(name = "is_primary_user")
	public Boolean getIsPrimaryUser() {
		return this.isPrimaryUser;
	}

	public void setIsPrimaryUser(final Boolean isPrimaryUser) {
		this.isPrimaryUser = isPrimaryUser;
	}

	@Column(name = "primary_user_id")
	public Integer getPrimaryUserId() {
		return this.primaryUserId;
	}

	public void setPrimaryUserId(final Integer primaryUserId) {
		this.primaryUserId = primaryUserId;
	}

	@Column(name = "has_internet_access")
	public Boolean getHasInternetAccess() {
		return this.hasInternetAccess;
	}

	public void setHasInternetAccess(final Boolean hasInternetAccess) {
		this.hasInternetAccess = hasInternetAccess;
	}

	@Column(name = "has_smsaccess")
	public Boolean getHasSmsaccess() {
		return this.hasSmsaccess;
	}

	public void setHasSmsaccess(final Boolean hasSmsaccess) {
		this.hasSmsaccess = hasSmsaccess;
	}

	@Column(name = "has_whatsapp_access")
	public Boolean getHasWhatsappAccess() {
		return this.hasWhatsappAccess;
	}

	public void setHasWhatsappAccess(final Boolean hasWhatsappAccess) {
		this.hasWhatsappAccess = hasWhatsappAccess;
	}

	@Column(name = "has_telegram_access")
	public Boolean getHasTelegramAccess() {
		return this.hasTelegramAccess;
	}

	public void setHasTelegramAccess(final Boolean hasTelegramAccess) {
		this.hasTelegramAccess = hasTelegramAccess;
	}

	@Column(name = "provides_location")
	public Boolean getProvidesLocation() {
		return this.providesLocation;
	}

	public void setProvidesLocation(final Boolean providesLocation) {
		this.providesLocation = providesLocation;
	}

}
