package com.covid.model;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PreExistingConditionCovidDenorm generated by hbm2java
 */
@Entity
@Table(name = "pre_existing_condition_covid_denorm", schema = "release1")
public class PreExistingConditionCovidDenorm implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -119348910906287167L;
	private int covidPreExistingConditionId;
	private int patientId;
	private Integer preExistingConditionId;
	private Boolean copd;
	private Boolean bronchitis;
	private Boolean diabetesMellitus;
	private Boolean diabetesMellitusType1;
	private Boolean diabetesMellitusType2;
	private Boolean hypertension;
	private Boolean chronicRenalDisease;
	private Boolean malignancy;
	private Boolean heartDisease;
	private Boolean asthma;
	private Boolean obesity;
	private String comments;

	public PreExistingConditionCovidDenorm() {
	}

	public PreExistingConditionCovidDenorm(final int covidPreExistingConditionId, final int patientId) {
		this.covidPreExistingConditionId = covidPreExistingConditionId;
		this.patientId = patientId;
	}

	public PreExistingConditionCovidDenorm(final int covidPreExistingConditionId, final int patientId,
			final Integer preExistingConditionId, final Boolean copd, final Boolean bronchitis,
			final Boolean diabetesMellitus, final Boolean diabetesMellitusType1, final Boolean diabetesMellitusType2,
			final Boolean hypertension, final Boolean chronicRenalDisease, final Boolean malignancy,
			final Boolean heartDisease, final Boolean asthma, final Boolean obesity, final String comments) {
		this.covidPreExistingConditionId = covidPreExistingConditionId;
		this.patientId = patientId;
		this.preExistingConditionId = preExistingConditionId;
		this.copd = copd;
		this.bronchitis = bronchitis;
		this.diabetesMellitus = diabetesMellitus;
		this.diabetesMellitusType1 = diabetesMellitusType1;
		this.diabetesMellitusType2 = diabetesMellitusType2;
		this.hypertension = hypertension;
		this.chronicRenalDisease = chronicRenalDisease;
		this.malignancy = malignancy;
		this.heartDisease = heartDisease;
		this.asthma = asthma;
		this.obesity = obesity;
		this.comments = comments;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "covid_pre_existing_condition_id", unique = true, nullable = false)
	public int getCovidPreExistingConditionId() {
		return this.covidPreExistingConditionId;
	}

	public void setCovidPreExistingConditionId(final int covidPreExistingConditionId) {
		this.covidPreExistingConditionId = covidPreExistingConditionId;
	}

	@Column(name = "patient_id", nullable = false)
	public int getPatientId() {
		return this.patientId;
	}

	public void setPatientId(final int patientId) {
		this.patientId = patientId;
	}

	@Column(name = "pre_existing_condition_id")
	public Integer getPreExistingConditionId() {
		return this.preExistingConditionId;
	}

	public void setPreExistingConditionId(final Integer preExistingConditionId) {
		this.preExistingConditionId = preExistingConditionId;
	}

	@Column(name = "copd")
	public Boolean getCopd() {
		return this.copd;
	}

	public void setCopd(final Boolean copd) {
		this.copd = copd;
	}

	@Column(name = "bronchitis")
	public Boolean getBronchitis() {
		return this.bronchitis;
	}

	public void setBronchitis(final Boolean bronchitis) {
		this.bronchitis = bronchitis;
	}

	@Column(name = "diabetes_mellitus")
	public Boolean getDiabetesMellitus() {
		return this.diabetesMellitus;
	}

	public void setDiabetesMellitus(final Boolean diabetesMellitus) {
		this.diabetesMellitus = diabetesMellitus;
	}

	@Column(name = "diabetes_mellitus_type_1")
	public Boolean getDiabetesMellitusType1() {
		return this.diabetesMellitusType1;
	}

	public void setDiabetesMellitusType1(final Boolean diabetesMellitusType1) {
		this.diabetesMellitusType1 = diabetesMellitusType1;
	}

	@Column(name = "diabetes_mellitus_type_2")
	public Boolean getDiabetesMellitusType2() {
		return this.diabetesMellitusType2;
	}

	public void setDiabetesMellitusType2(final Boolean diabetesMellitusType2) {
		this.diabetesMellitusType2 = diabetesMellitusType2;
	}

	@Column(name = "hypertension")
	public Boolean getHypertension() {
		return this.hypertension;
	}

	public void setHypertension(final Boolean hypertension) {
		this.hypertension = hypertension;
	}

	@Column(name = "chronic_renal_disease")
	public Boolean getChronicRenalDisease() {
		return this.chronicRenalDisease;
	}

	public void setChronicRenalDisease(final Boolean chronicRenalDisease) {
		this.chronicRenalDisease = chronicRenalDisease;
	}

	@Column(name = "malignancy")
	public Boolean getMalignancy() {
		return this.malignancy;
	}

	public void setMalignancy(final Boolean malignancy) {
		this.malignancy = malignancy;
	}

	@Column(name = "heart_disease")
	public Boolean getHeartDisease() {
		return this.heartDisease;
	}

	public void setHeartDisease(final Boolean heartDisease) {
		this.heartDisease = heartDisease;
	}

	@Column(name = "asthma")
	public Boolean getAsthma() {
		return this.asthma;
	}

	public void setAsthma(final Boolean asthma) {
		this.asthma = asthma;
	}

	@Column(name = "obesity")
	public Boolean getObesity() {
		return this.obesity;
	}

	public void setObesity(final Boolean obesity) {
		this.obesity = obesity;
	}

	@Column(name = "comments")
	public String getComments() {
		return this.comments;
	}

	public void setComments(final String comments) {
		this.comments = comments;
	}

}
