package com.covid.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UserPhoto generated by hbm2java
 */
@Entity
@Table(name = "user_photo", schema = "release1")
public class UserPhoto implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -2634209156575573436L;
	private int photoId;
	private int userId;
	private String photoType;
	private String photoPath;
	private Date fileSavedDatetime;

	public UserPhoto() {
	}

	public UserPhoto(final int photoId, final int userId) {
		this.photoId = photoId;
		this.userId = userId;
	}

	public UserPhoto(final int photoId, final int userId, final String photoType, final String photoPath,
			final Date fileSavedDatetime) {
		this.photoId = photoId;
		this.userId = userId;
		this.photoType = photoType;
		this.photoPath = photoPath;
		this.fileSavedDatetime = fileSavedDatetime;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "photo_id", unique = true, nullable = false)
	public int getPhotoId() {
		return this.photoId;
	}

	public void setPhotoId(final int photoId) {
		this.photoId = photoId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(final int userId) {
		this.userId = userId;
	}

	@Column(name = "photo_type", length = 32)
	public String getPhotoType() {
		return this.photoType;
	}

	public void setPhotoType(final String photoType) {
		this.photoType = photoType;
	}

	@Column(name = "photo_path", length = 150)
	public String getPhotoPath() {
		return this.photoPath;
	}

	public void setPhotoPath(final String photoPath) {
		this.photoPath = photoPath;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "file_saved_datetime", length = 29)
	public Date getFileSavedDatetime() {
		return this.fileSavedDatetime;
	}

	public void setFileSavedDatetime(final Date fileSavedDatetime) {
		this.fileSavedDatetime = fileSavedDatetime;
	}

}
