package com.covid.model;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
// Generated May 1, 2020, 8:54:03 PM by Hibernate Tools 5.2.12.Final
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Users generated by hbm2java
 */
@Entity
@Table(name = "users", schema = "release1")
public class Users implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 1095759871613455259L;
	private int userId;
	private String title;
	private String firstName;
	private String middleName;
	private String lastName;
	private String longFullName;
	private String shortFullName;
	private String displayName;
	private String lsFirstName;
	private String lsMiddleName;
	private String lsLastName;
	private String lsLongFullName;
	private String lsShortFullName;
	private String lsDisplayName;
	private String suffix;
	private String degree;
	private Date dateOfBirth;
	private Short ageYrs;
	private String adminGender;
	private String biologicalSex;
	private String otpCode;

	public Users() {
	}

	public Users(final int userId) {
		this.userId = userId;
	}

	public Users(final int userId, final String title, final String firstName, final String middleName,
			final String lastName, final String longFullName, final String shortFullName, final String displayName,
			final String lsFirstName, final String lsMiddleName, final String lsLastName, final String lsLongFullName,
			final String lsShortFullName, final String lsDisplayName, final String suffix, final String degree,
			final Date dateOfBirth, final Short ageYrs, final String adminGender, final String biologicalSex,
			final String otpCode) {
		this.userId = userId;
		this.title = title;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.longFullName = longFullName;
		this.shortFullName = shortFullName;
		this.displayName = displayName;
		this.lsFirstName = lsFirstName;
		this.lsMiddleName = lsMiddleName;
		this.lsLastName = lsLastName;
		this.lsLongFullName = lsLongFullName;
		this.lsShortFullName = lsShortFullName;
		this.lsDisplayName = lsDisplayName;
		this.suffix = suffix;
		this.degree = degree;
		this.dateOfBirth = dateOfBirth;
		this.ageYrs = ageYrs;
		this.adminGender = adminGender;
		this.biologicalSex = biologicalSex;
		this.otpCode = otpCode;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)

	@Column(name = "user_id", unique = true, nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(final int userId) {
		this.userId = userId;
	}

	@Column(name = "title", length = 16)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(final String title) {
		this.title = title;
	}

	@Column(name = "first_name", length = 32)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(final String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "middle_name", length = 32)
	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(final String middleName) {
		this.middleName = middleName;
	}

	@Column(name = "last_name", length = 32)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(final String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "long_full_name", length = 100)
	public String getLongFullName() {
		return this.longFullName;
	}

	public void setLongFullName(final String longFullName) {
		this.longFullName = longFullName;
	}

	@Column(name = "short_full_name", length = 30)
	public String getShortFullName() {
		return this.shortFullName;
	}

	public void setShortFullName(final String shortFullName) {
		this.shortFullName = shortFullName;
	}

	@Column(name = "display_name", length = 16)
	public String getDisplayName() {
		return this.displayName;
	}

	public void setDisplayName(final String displayName) {
		this.displayName = displayName;
	}

	@Column(name = "ls_first_name", length = 32)
	public String getLsFirstName() {
		return this.lsFirstName;
	}

	public void setLsFirstName(final String lsFirstName) {
		this.lsFirstName = lsFirstName;
	}

	@Column(name = "ls_middle_name", length = 32)
	public String getLsMiddleName() {
		return this.lsMiddleName;
	}

	public void setLsMiddleName(final String lsMiddleName) {
		this.lsMiddleName = lsMiddleName;
	}

	@Column(name = "ls_last_name", length = 32)
	public String getLsLastName() {
		return this.lsLastName;
	}

	public void setLsLastName(final String lsLastName) {
		this.lsLastName = lsLastName;
	}

	@Column(name = "ls_long_full_name", length = 100)
	public String getLsLongFullName() {
		return this.lsLongFullName;
	}

	public void setLsLongFullName(final String lsLongFullName) {
		this.lsLongFullName = lsLongFullName;
	}

	@Column(name = "ls_short_full_name", length = 30)
	public String getLsShortFullName() {
		return this.lsShortFullName;
	}

	public void setLsShortFullName(final String lsShortFullName) {
		this.lsShortFullName = lsShortFullName;
	}

	@Column(name = "ls_display_name", length = 16)
	public String getLsDisplayName() {
		return this.lsDisplayName;
	}

	public void setLsDisplayName(final String lsDisplayName) {
		this.lsDisplayName = lsDisplayName;
	}

	@Column(name = "suffix", length = 16)
	public String getSuffix() {
		return this.suffix;
	}

	public void setSuffix(final String suffix) {
		this.suffix = suffix;
	}

	@Column(name = "degree", length = 16)
	public String getDegree() {
		return this.degree;
	}

	public void setDegree(final String degree) {
		this.degree = degree;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_of_birth", length = 29)
	public Date getDateOfBirth() {
		return this.dateOfBirth;
	}

	public void setDateOfBirth(final Date dateOfBirth) {
		this.dateOfBirth = dateOfBirth;
	}

	@Column(name = "age_yrs")
	public Short getAgeYrs() {
		return this.ageYrs;
	}

	public void setAgeYrs(final Short ageYrs) {
		this.ageYrs = ageYrs;
	}

	@Column(name = "admin_gender", length = 32)
	public String getAdminGender() {
		return this.adminGender;
	}

	public void setAdminGender(final String adminGender) {
		this.adminGender = adminGender;
	}

	@Column(name = "biological_sex", length = 32)
	public String getBiologicalSex() {
		return this.biologicalSex;
	}

	public void setBiologicalSex(final String biologicalSex) {
		this.biologicalSex = biologicalSex;
	}

	@Column(name = "otp_code")
	public String getOtpCode() {
		return this.otpCode;
	}

	public void setOtpCode(final String otpCode) {
		this.otpCode = otpCode;
	}

}
